### ISSUE TITLE
Propagation of CUDA out of memory error

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#188]
Hi,
I am getting the following errors:

```
../PyNvCodec/TC/src/NvDecoder.cpp:338
CUDA error: CUDA_ERROR_OUT_OF_MEMORY
out of memory
```

To reproduce the error I am using the following script modification of  [SampleDecodeMultiThread.py](https://github.com/NVIDIA/VideoProcessingFramework/blob/master/SampleDecodeMultiThread.py)

Instantiating decoder 50 times.

```python

import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), "build/PyNvCodec"))
import PyNvCodec as nvc
import numpy as np
import sys

from threading import Thread

class Worker(Thread):
    def __init__(self, gpuID, encFile):
        Thread.__init__(self)

        #self.nvDec = nvc.PyNvDecoder(encFile, gpuID, {'rtsp_transport': 'tcp', 'max_delay': '5000000', 'bufsize': '30000k'})
        self.nvDec = nvc.PyNvDecoder(encFile, gpuID)
        
        width, height = self.nvDec.Width(), self.nvDec.Height()
        hwidth, hheight = int(width / 2), int(height / 2)

        self.nvCvt = nvc.PySurfaceConverter(width, height, self.nvDec.Format(), nvc.PixelFormat.YUV420, gpuID)
        self.nvRes = nvc.PySurfaceResizer(hwidth, hheight, self.nvCvt.Format(), gpuID)
        self.nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, self.nvRes.Format(), gpuID)
        self.num_frame = 0

    def run(self):
        try:
            while True:
                try:
                    rawSurface = self.nvDec.DecodeSingleSurface()
                    if (rawSurface.Empty()):
                        print('No more video frames')
                        break
                except nvc.HwResetException:
                    print('Continue after HW decoder was reset')
                    continue
 
                cvtSurface = self.nvCvt.Execute(rawSurface)
                if (cvtSurface.Empty()):
                    print('Failed to do color conversion')
                    break

                resSurface = self.nvRes.Execute(cvtSurface)
                if (resSurface.Empty()):
                    print('Failed to resize surface')
                    break
 
                rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
                success = self.nvDwn.DownloadSingleSurface(resSurface, rawFrame)
                if not (success):
                    print('Failed to download surface')
                    break
 
                self.num_frame += 1
                if( 0 == self.num_frame % self.nvDec.Framerate() ):
                    print(self.num_frame)
 
        except Exception as e:
            print(getattr(e, 'message', str(e)))
            # decFile.close()
 
def create_threads(gpu_id1, input_file1, gpu_id2, input_file2):
    th_list = []
    for _ in range(50):
        th_list.append(Worker(gpu_id1, input_file1))
    for th in th_list:
        th.start()

    for th in th_list:
        th.join()

 
    # th1  = Worker(gpu_id1, input_file1)
    # th2  = Worker(gpu_id1, input_file1)
 
    # th1.start()
    # th2.start()
 
    # th1.join()
    # th2.join()
 
if __name__ == "__main__":

    print('This sample decodes video stream in 2 parallel threads. It does not save output.')
    print('GPU-accelerated color conversion and resize are also applied.')
    print('Network input such as RTSP is supported as well.')
    print('This sample may serve as a stability test.')
    print('Usage: python SampleDecodeMultiThread.py $gpu_id_0 $input_0 $gpu_id_1 $input_1')
 
    if(len(sys.argv) < 3):
        print("Provide input CLI arguments as shown above")
        exit(1)
 
    gpu_1 = int(sys.argv[1])
    input_1 = sys.argv[2]
    # gpu_2 = int(sys.argv[3])
    # input_2 = sys.argv[4]
    gpu_2 = 0
    input_2 = ""
 
    create_threads(gpu_1, input_1, gpu_2, input_2)

```
How to propagate the CUDA out of memory error to calling thread, without seg faulting the library? The sources of the exception are `noexcept` functions like the followings.

https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/TC/src/NvDecoder.cpp#L194-L347

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

I've pushed a patch to `issue_188` branch which adds a flag for cuvid parser errors same way it foes for decoder:
https://github.com/NVIDIA/VideoProcessingFramework/blob/2930606ffae22c490229d130aaeeccfa0c4f69fc/PyNvCodec/TC/src/NvDecoder.cpp#L185-L186

Now `NvDecoder::HandleVideoSequence`, `NvDecoder::HandlePictureDecode` and `NvDecoder::HandlePictureDisplay` functions set up this flag in case of error. 

The flag is checked every time the `NvDecoder::DecodeLockSurface` method is called which is single entry point to HW decode:
https://github.com/NVIDIA/VideoProcessingFramework/blob/2930606ffae22c490229d130aaeeccfa0c4f69fc/PyNvCodec/TC/src/NvDecoder.cpp#L667-L680

This exception shall propagate all the way up to Python.
Please check out the `issue_188` branch and test if it solves the issue.

**Comment by vtpl1** [comment]
Thank you @rarzumanyan , the fix looks good. testing more rigorously before closing the the issue.

**Comment by vtpl1** [comment]
Hi @rarzumanyan ,
The issue is not resolved yet.
Getting 
`Exception thrown during decoding process`

https://github.com/NVIDIA/VideoProcessingFramework/blob/2930606ffae22c490229d130aaeeccfa0c4f69fc/PyNvCodec/src/PyNvCodec.cpp#L474-L479


Need to distinguish between `VPF::HwResetException` and `std::runtime_error`.
and define the define what is causing `VPF::HwResetException` and what would be system's behaviour. Should upper layer just continue in case of `VPF::HwResetException` or break the loop?

**Comment by rarzumanyan** [comment]
@vtpl1 

Thanks for the update.
Check out `issue_188` ToT, I've registered additional exception of type `CuvidParserException` which is thrown to Python land in case of parser exceptions alongside existing `HwResetException` which is thrown in case of hw decoder errors.

**Comment by vtpl1** [comment]
@rarzumanyan ,
The issue is probably still there. Trying to narrow down the script to re-produce.

To be on the same page:
If `CUDA_ERROR_OUT_OF_MEMORY` occurs in a decoder thread only that thread should receive the exception and stop without affecting the other running threads.

But as the `CUDA_ERROR_OUT_OF_MEMORY`  happening in multiple threads simultaneously, which is creating the Segmentation fault (core dumped).

**Comment by rarzumanyan** [comment]
@vtpl1 

I assume you're referencing highly simplified script which spawns 50 threads only to illustrate the behavior, right?
If you do some heavy-duty video processing with massive amount of videos being decoded in parallel threads I recommend you to monitor the amount of available gpu memory with `py3nvml` library.

There are 3 places where the memory is allocated in VPF:
1. `SurfacePlane::Allocate()`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/TC/src/MemoryInterfaces.cpp#L277-L291
2. `NvDecoder::HandlePictureDisplay()`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/TC/src/NvDecoder.cpp#L512-L529
3. `NvEncoderCuda::AllocateInputBuffers()`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/TC/src/NvEncoderCuda.cpp#L58-L73

Only `NvDecoder::HandlePictureDisplay()` does memory allocation "under the hood". During the encoding, decoding & processing `PyNvEncoder` allocates the input buffers upon constructor call or encoder reconfigure. Beside that, all kinds of surface converters, uploaders and downloaders are allocating memory upon constructor call.

So, the out of memory surprise may happen mostly when you're decoding because decoder may need more memory to store video frames upon video sequence parameters change, if output frames are locked slower then new frames are coming from decoder etc. My recommendation here is to closely watch amount of free GPU memory because if decoder needs to map decoded frame to CUDA memory and it can't, the decoding process is mostly screwed and you need to start over.

I'm not 100% sure how that may cause segfault error so I'll continue the investigation after your triage.

**Comment by vtpl1** [comment]
Hi @rarzumanyan , thank you for the detailed explanation, under memory pressure the application still crash if we don't keep sufficient margin for memory allocation
Closing the issue for now.

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

After some investigation done on my machine with 2 different GPUs, I'd like to share my conclusions with you:

1. It's better to use subprocesses instead of threads for maximum performance.
2. Quadro GPU is much more persistent then GeForce GPU in terms of massive parallel loads handing.

Using snippet below I was able to run 128 decoding processes in parallel. 4 of them failed due to lack of GPU memory and were killed by Windows task manager, rest 124 were running:
```python
import PyNvCodec as nvc
import numpy as np
import sys

from multiprocessing import Process

def dec_function(gpuID, encFile, id):
    try:
        nvDec = nvc.PyNvDecoder(encFile, gpuID)
        
        width, height = nvDec.Width(), nvDec.Height()
        hwidth, hheight = int(width / 2), int(height / 2)

        nvCvt = nvc.PySurfaceConverter(width, height, nvDec.Format(), nvc.PixelFormat.YUV420, gpuID)
        nvRes = nvc.PySurfaceResizer(hwidth, hheight, nvCvt.Format(), gpuID)
        nvDwn = nvc.PySurfaceDownloader(hwidth, hheight, nvRes.Format(), gpuID)
        num_frame = 0
    
        while True:
            try:
                rawSurface = nvDec.DecodeSingleSurface()
                if (rawSurface.Empty()):
                    print(id, ': No more video frames')
                    break
            except nvc.HwResetException:
                print(id, ': Continue after HW decoder was reset')
                continue
 
            cvtSurface = nvCvt.Execute(rawSurface)
            if (cvtSurface.Empty()):
                print(id, ': Failed to do color conversion')
                break

            resSurface = nvRes.Execute(cvtSurface)
            if (resSurface.Empty()):
                print(id, ': Failed to resize surface')
                break
 
            rawFrame = np.ndarray(shape=(resSurface.HostSize()), dtype=np.uint8)
            success = nvDwn.DownloadSingleSurface(resSurface, rawFrame)
            if not (success):
                print(id, ': Failed to download surface')
                break
 
            num_frame += 1
            if(0 == num_frame % nvDec.Framerate()):
                print(id, ': ', num_frame)
 
    except Exception as e:
        print(getattr(e, 'message', str(e)))
        decFile.close()
 
def create_procs(gpu_id, input_file):
    proc_list = []

    for idx in range(128):
        proc_list.append(Process(target=dec_function, args=(gpu_id, input_file, idx)))

    for proc in proc_list:
        proc.start()

    for proc in proc_list:
        proc.join()

 
if __name__ == "__main__":
    if(len(sys.argv) < 3):
        print("Provide gpu_id and input file path")
        exit(1)
 
    gpu_id = int(sys.argv[1])
    input_file = sys.argv[2]
    create_procs(gpu_id, input_file)
```

On my RTX 3080 under memory pressure many CUDA functions were returning error codes showing that CUDA capable devices are busy and unavailable although the VPF library didn't segfault.

Quadro RTX5000 was much more stable, failing processes were killed by task manager and process went on.

However, I still highly recommend to use some kind of managed approach to your parallel decoding which will take into account existing GPU resources every time you spawn extra decoding session.

**Comment by vtpl1** [comment]
Hi @rarzumanyan, thank you for your elaboration, may I know why did you tried to do it in multiple process instead of multiple threads?
I think you tried to by pass the GIL, in my forked version I got rid of GIL by proper use of pybind11 GIL release. If you want I can do a pr.

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

>may I know why did you tried to do it in multiple process instead of multiple threads?
>in my forked version I got rid of GIL by proper use of pybind11 GIL release

Some time ago there was a nasty issue related to heap corruption which was only reproducing in multithread mode but not in multi-process mode so I've made a multi-threaded sample as it's a good reproducer for all sorts of bugs.

>  If you want I can do a pr.

Please go ahead and do PR, I'd really like to see proper GIL block and release in action.
Maybe it will also reproduce a segfault library behavior.
